---
- name: get host count
  uri: 
    url: "https://{{ tower_host }}/api/v2/hosts/?page_size={{ _page_size }}&page=1"
    method: GET
    validate_certs: "{{ tower_validate_ssl }}"
    user: "{{ tower_username }}"
    password: "{{ tower_password }}"
    force_basic_auth: yes
  register: tower_hosts_count
  
- name: debug tower_hosts_count
  when: debug
  copy:
    dest: tower_hosts_count.json
    content: "{{ tower_hosts_count }}"
    force: yes

- name: get host pages
  loop: "{{ range(1 , (tower_hosts_count.json.count / _page_size) | round(0,'ceil') | int + 1 ) | list }}"
  uri:
    url: "https://{{ tower_host }}/api/v2/hosts/?page_size={{ _page_size }}&page={{ item }}"
    method: GET
    validate_certs: "{{ tower_validate_ssl }}"
    user: "{{ tower_username }}"
    password: "{{ tower_password }}"
    force_basic_auth: yes
  register: tower_hosts_pages

- name: debug tower_hosts_pages
  when: debug
  copy:
    dest: tower_hosts_pages.json
    content: "{{ tower_hosts_pages }}"
    force: yes

- name: collect hosts as list
  set_fact:
    tower_hosts_list: "{{ lookup('template', 'templates/tower_hosts_list.j2') }}"

- name: debug tower_hosts_list
  when: debug
  copy:
    dest: tower_hosts_list.json
    content: "{{ tower_hosts_list }}"
    force: yes

- name: collect hosts as dict by id
  set_fact:
    tower_hosts_dict_id: "{{ lookup('template', 'templates/tower_hosts_dict_id.j2') }}"

- name: debug tower_hosts_dict_id
  when: debug
  copy:
    dest: tower_hosts_dict_id.json
    content: "{{ tower_hosts_dict_id }}"
    force: yes

- name: collect ansible_host
  loop: "{{ tower_hosts_list }}"
  when: item.variables != '' and  unique_var in item.variables | from_yaml
  no_log: true
  set_fact:
    ansible_host_list: "{{ ansible_host_list | default([]) }} + {{ [(item.variables | from_yaml)[unique_var]] }}"

- name: debug ansible_host_list
  when: debug and ansible_host_list is defined
  copy:
    dest: ansible_host_list.json
    content: "{{ ansible_host_list }}"
    force: yes

- name: collect inventory_hostname
  loop: "{{ tower_hosts_list }}"
  when: item.variables == '' or unique_var not in item.variables | from_yaml
  no_log: true
  set_fact:
    inventory_hostname_list: "{{ inventory_hostname_list | default([]) }} + {{ [item.name] }}"

- name: debug inventory_hostname_list
  when: debug and inventory_hostname_list is defined
  copy:
    dest: inventory_hostname_list.json
    content: "{{ inventory_hostname_list }}"
    force: yes   

- name: collect unique hosts
  set_fact:
    unique_hosts: "{{ (ansible_host_list | default ([]) + inventory_hostname_list | default([])) | unique }}"

- name: debug unique_hosts
  when: debug
  copy:
    dest: unique_hosts.json
    content: "{{ unique_hosts }}"
    force: yes
