---
- name: get license
  uri: 
    url: "https://{{ tower_host }}/api/v2/config/"
    method: GET
    validate_certs: "{{ tower_validate_ssl }}"
    user: "{{ tower_username }}"
    password: "{{ tower_password }}"
    force_basic_auth: yes
  register: tower_license

- name: Get Hosts
  include_tasks: gethosts.yml

- name: Get Organizations
  include_tasks: getorgs.yml

- name: count hosts
  loop: "{{ tower_hosts_list }}"
  no_log: yes
  set_fact:
    tower_org_host_count: "{{ tower_org_host_count | combine(
      { tower_orgs_dict_id[item.summary_fields.inventory.organization_id].name: 
      tower_org_host_count[tower_orgs_dict_id[item.summary_fields.inventory.organization_id].name] | default(0) + 1 }
      ) }}"
  vars:
    - tower_org_host_count: {}

- name: create html report
  template:
    src: templates/report.html.j2
    dest: "{{ html_report_path }}"
  ignore_errors: yes
  when: html_report