---
org_node_quotas:
  Default: "{{ tower_license.json.license_info.instance_count }}"


tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
tower_validate_ssl: "{{ lookup('env', 'TOWER_VERIFY_SSL') | default('false')}}"
_page_size: 100
debug: no
html_report: no
html_report_path: "{{ playbook_dir }}/report.html"